#!/usr/bin/env sh

files=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.json$")

for file in $files; do
    if [[ $file == *.json ]]; then
        if ! jq . "$file" > /dev/null 2>&1; then
            echo "ERROR: JSON invàlid a $file"
            exit 1
        fi
    fi
done

exit 0