name: GitHub Actions Demo Tag Python
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  create:
    tag: [v.*.*]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
    - run: chmod +x my_script.py
    - run: python my_script.py