name: Demo variable de workflow 1
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
env:
  VARIABLE_2: Variable 2 de workflow
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ vars.VARIABLE_1 }}" 
    - run: echo "${{ env.VARIABLE_2 }}" 
    - run: echo "${{ env.VARIABLE_2 }}" 
      env:
        VARIABLE_2: Nueva variable 2