name: Demo variable de workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [workflow_dispatch]
env:
  VARIABLE_2: Variable 2 de workflow
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo Variable1: "${{ vars.VARIABLE_1 }}" 
    - run: echo Variable2: "${{ env.VARIABLE_2 }}" 
    - run: echo Variable2: "${{ env.VARIABLE_2 }}" 
      env: 
        VARIABLE_2: Nova variable 2
	