name: Demo secreto
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  [workflow_dispatch]
jobs:
  secreto:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt install zip
    - run: unzip -P {{secrets.ZIP_PASS}} secret.zip   
    - run: cat secret.txt